"""1 migrations

Revision ID: 11573c122016
Revises: a1bc80bdb7e7
Create Date: 2023-10-18 18:31:30.406928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11573c122016'
down_revision: Union[str, None] = 'a1bc80bdb7e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('delivery', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('takeaway', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('dinein', sa.Boolean(), nullable=True))
    op.drop_column('products', 'type_takeaway')
    op.drop_column('products', 'type_dinein')
    op.drop_column('products', 'type_delivery')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('type_delivery', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('type_dinein', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('type_takeaway', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('products', 'dinein')
    op.drop_column('products', 'takeaway')
    op.drop_column('products', 'delivery')
    # ### end Alembic commands ###
