"""2 migrations

Revision ID: a229dacdf742
Revises: f12d507c5c6d
Create Date: 2023-10-06 17:41:00.331057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a229dacdf742'
down_revision: Union[str, None] = 'f12d507c5c6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_column('users', 'availability')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('availability', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
