"""1 migrations

Revision ID: 6e20a77a89e4
Revises: e342d8aa48e8
Create Date: 2023-12-19 17:07:23.659387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e20a77a89e4'
down_revision: Union[str, None] = 'e342d8aa48e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bot_tokens_user_id_fkey', 'bot_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'bot_tokens', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('categories_created_by_fkey', 'categories', type_='foreignkey')
    op.drop_constraint('categories_updated_by_fkey', 'categories', type_='foreignkey')
    op.drop_constraint('categories_deleted_by_fkey', 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'users', ['updated_by'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'categories', 'users', ['created_by'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'categories', 'users', ['deleted_by'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('mail_images_created_by_fkey', 'mail_images', type_='foreignkey')
    op.drop_constraint('mail_images_deleted_by_fkey', 'mail_images', type_='foreignkey')
    op.create_foreign_key(None, 'mail_images', 'users', ['deleted_by'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'mail_images', 'users', ['created_by'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('mails_created_by_fkey', 'mails', type_='foreignkey')
    op.drop_constraint('mails_deleted_by_fkey', 'mails', type_='foreignkey')
    op.create_foreign_key(None, 'mails', 'users', ['deleted_by'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'mails', 'users', ['created_by'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('orders_order_type_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_order_status_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'order_types', ['order_type_id'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'orders', 'order_status', ['order_status_id'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('products_updated_by_fkey', 'products', type_='foreignkey')
    op.drop_constraint('products_unit_id_fkey', 'products', type_='foreignkey')
    op.drop_constraint('products_deleted_by_fkey', 'products', type_='foreignkey')
    op.drop_constraint('products_created_by_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'units', ['unit_id'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'products', 'users', ['deleted_by'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'products', 'users', ['updated_by'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'products', 'users', ['created_by'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('store_order_types_association_order_type_id_fkey', 'store_order_types_association', type_='foreignkey')
    op.create_foreign_key(None, 'store_order_types_association', 'order_types', ['order_type_id'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('stores_deleted_by_fkey', 'stores', type_='foreignkey')
    op.drop_constraint('stores_created_by_fkey', 'stores', type_='foreignkey')
    op.drop_constraint('stores_updated_by_fkey', 'stores', type_='foreignkey')
    op.drop_constraint('stores_user_id_fkey', 'stores', type_='foreignkey')
    op.create_foreign_key(None, 'stores', 'users', ['deleted_by'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'stores', 'users', ['updated_by'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'stores', 'users', ['created_by'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'stores', 'users', ['user_id'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('subcategories_created_by_fkey', 'subcategories', type_='foreignkey')
    op.drop_constraint('subcategories_updated_by_fkey', 'subcategories', type_='foreignkey')
    op.drop_constraint('subcategories_deleted_by_fkey', 'subcategories', type_='foreignkey')
    op.create_foreign_key(None, 'subcategories', 'users', ['created_by'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'subcategories', 'users', ['deleted_by'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'subcategories', 'users', ['updated_by'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('tokens_user_id_fkey', 'tokens', type_='foreignkey')
    op.create_foreign_key(None, 'tokens', 'users', ['user_id'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('users_role_id_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_employee_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'users', 'employees', ['employee_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('working_days_day_of_week_id_fkey', 'working_days', type_='foreignkey')
    op.create_foreign_key(None, 'working_days', 'days_of_week', ['day_of_week_id'], ['id'], referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'working_days', type_='foreignkey')
    op.create_foreign_key('working_days_day_of_week_id_fkey', 'working_days', 'days_of_week', ['day_of_week_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'users', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'users', schema='public', type_='foreignkey')
    op.create_foreign_key('users_employee_id_fkey', 'users', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('users_role_id_fkey', 'users', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'tokens', type_='foreignkey')
    op.create_foreign_key('tokens_user_id_fkey', 'tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'subcategories', type_='foreignkey')
    op.drop_constraint(None, 'subcategories', type_='foreignkey')
    op.drop_constraint(None, 'subcategories', type_='foreignkey')
    op.create_foreign_key('subcategories_deleted_by_fkey', 'subcategories', 'users', ['deleted_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('subcategories_updated_by_fkey', 'subcategories', 'users', ['updated_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('subcategories_created_by_fkey', 'subcategories', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.create_foreign_key('stores_user_id_fkey', 'stores', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('stores_updated_by_fkey', 'stores', 'users', ['updated_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('stores_created_by_fkey', 'stores', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('stores_deleted_by_fkey', 'stores', 'users', ['deleted_by'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'store_order_types_association', type_='foreignkey')
    op.create_foreign_key('store_order_types_association_order_type_id_fkey', 'store_order_types_association', 'order_types', ['order_type_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_created_by_fkey', 'products', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('products_deleted_by_fkey', 'products', 'users', ['deleted_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('products_unit_id_fkey', 'products', 'units', ['unit_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('products_updated_by_fkey', 'products', 'users', ['updated_by'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_order_status_id_fkey', 'orders', 'order_status', ['order_status_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('orders_order_type_id_fkey', 'orders', 'order_types', ['order_type_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'mails', type_='foreignkey')
    op.drop_constraint(None, 'mails', type_='foreignkey')
    op.create_foreign_key('mails_deleted_by_fkey', 'mails', 'users', ['deleted_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('mails_created_by_fkey', 'mails', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'mail_images', type_='foreignkey')
    op.drop_constraint(None, 'mail_images', type_='foreignkey')
    op.create_foreign_key('mail_images_deleted_by_fkey', 'mail_images', 'users', ['deleted_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('mail_images_created_by_fkey', 'mail_images', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key('categories_deleted_by_fkey', 'categories', 'users', ['deleted_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('categories_updated_by_fkey', 'categories', 'users', ['updated_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('categories_created_by_fkey', 'categories', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'bot_tokens', schema='public', type_='foreignkey')
    op.create_foreign_key('bot_tokens_user_id_fkey', 'bot_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
