"""1 migrations

Revision ID: 5500144426d2
Revises: 0b4687714afc
Create Date: 2023-10-22 13:26:34.530612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5500144426d2'
down_revision: Union[str, None] = '0b4687714afc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'availability',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'availability',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
