"""1 migrations

Revision ID: ba95c634a771
Revises: f56a77933b58
Create Date: 2023-10-20 18:22:26.345587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba95c634a771'
down_revision: Union[str, None] = 'f56a77933b58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'availability')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('availability', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
