"""1 migrations

Revision ID: 2ae6107891b4
Revises: b2ceef6bcb14
Create Date: 2023-11-02 16:52:03.367681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ae6107891b4'
down_revision: Union[str, None] = 'b2ceef6bcb14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_access_token'), 'tokens', ['access_token'], unique=True)
    op.create_index(op.f('ix_tokens_id'), 'tokens', ['id'], unique=False)
    op.drop_constraint('categories_deleted_by_fkey', 'categories', type_='foreignkey')
    op.drop_constraint('categories_updated_by_fkey', 'categories', type_='foreignkey')
    op.drop_constraint('categories_created_by_fkey', 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'users', ['created_by'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'categories', 'users', ['deleted_by'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'categories', 'users', ['updated_by'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('products_updated_by_fkey', 'products', type_='foreignkey')
    op.drop_constraint('products_created_by_fkey', 'products', type_='foreignkey')
    op.drop_constraint('products_deleted_by_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'users', ['updated_by'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'products', 'users', ['created_by'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'products', 'users', ['deleted_by'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('subcategories_updated_by_fkey', 'subcategories', type_='foreignkey')
    op.drop_constraint('subcategories_deleted_by_fkey', 'subcategories', type_='foreignkey')
    op.drop_constraint('subcategories_created_by_fkey', 'subcategories', type_='foreignkey')
    op.create_foreign_key(None, 'subcategories', 'users', ['deleted_by'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'subcategories', 'users', ['created_by'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'subcategories', 'users', ['updated_by'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('users_employee_id_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_role_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'users', 'employees', ['employee_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'users', schema='public', type_='foreignkey')
    op.create_foreign_key('users_role_id_fkey', 'users', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('users_employee_id_fkey', 'users', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'subcategories', type_='foreignkey')
    op.drop_constraint(None, 'subcategories', type_='foreignkey')
    op.drop_constraint(None, 'subcategories', type_='foreignkey')
    op.create_foreign_key('subcategories_created_by_fkey', 'subcategories', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('subcategories_deleted_by_fkey', 'subcategories', 'users', ['deleted_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('subcategories_updated_by_fkey', 'subcategories', 'users', ['updated_by'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_deleted_by_fkey', 'products', 'users', ['deleted_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('products_created_by_fkey', 'products', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('products_updated_by_fkey', 'products', 'users', ['updated_by'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key('categories_created_by_fkey', 'categories', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('categories_updated_by_fkey', 'categories', 'users', ['updated_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('categories_deleted_by_fkey', 'categories', 'users', ['deleted_by'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tokens_id'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_access_token'), table_name='tokens')
    op.drop_table('tokens')
    # ### end Alembic commands ###
