"""1 migrations

Revision ID: 3d5515db2827
Revises: 587118969d63
Create Date: 2023-10-17 15:29:43.830220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d5515db2827'
down_revision: Union[str, None] = '587118969d63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('categories_shop_id_fkey', 'categories', type_='foreignkey')
    op.drop_column('categories', 'shop_id')
    op.drop_column('categories', 'name_en')
    op.drop_column('categories', 'availability')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('availability', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('categories', sa.Column('name_en', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('categories', sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('categories_shop_id_fkey', 'categories', 'users', ['shop_id'], ['id'])
    # ### end Alembic commands ###
