"""1 migrations

Revision ID: 8ee4f03056ea
Revises: 6e14da169e67
Create Date: 2023-10-20 14:06:40.480399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ee4f03056ea'
down_revision: Union[str, None] = '6e14da169e67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'name_rus',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('categories', 'availability',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'availability',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('categories', 'name_rus',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
