"""1 migrations

Revision ID: ac79fece1d9a
Revises: 3d5515db2827
Create Date: 2023-10-18 16:45:13.927014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac79fece1d9a'
down_revision: Union[str, None] = '3d5515db2827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('availability', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('type_dinein', sa.Boolean(), nullable=True))
    op.drop_constraint('products_shop_id_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'shop_id')
    op.drop_column('products', 'name_en')
    op.drop_column('products', 'type_inside')
    op.drop_column('products', 'description_en')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description_en', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('type_inside', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('name_en', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('products_shop_id_fkey', 'products', 'users', ['shop_id'], ['id'])
    op.drop_column('products', 'type_dinein')
    op.drop_column('categories', 'availability')
    # ### end Alembic commands ###
