from .models import (
    Store,
    BotToken,
    OrderType,
    StoreOrderTypeAssociation,
    StoreInfo,
    StoreSubscription,
    DayOfWeek,
    WorkingDay,
    StorePayment,
    ServiceTextAndChat,
    LegalInformation,
    DeliveryDistance,
    DeliveryFix,
    DeliveryDistrict,
)

all = [
    Store,
    BotToken,
    OrderType,
    StoreOrderTypeAssociation,
    StoreInfo,
    StoreSubscription,
    DayOfWeek,
    WorkingDay,
    StorePayment,
    ServiceTextAndChat,
    LegalInformation,
    DeliveryDistance,
    DeliveryFix,
    DeliveryDistrict,
]
